server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # ถ้าหาไฟล์ไม่เจอ ให้โยนกลับไปที่ index.html เพื่อให้ React Router จัดการต่อ
        try_files $uri $uri/ /index.html;
    }
}