version: '3.8'

services:
  # ฐานข้อมูล MySQL
  mysql-db:
    image: mysql:8.0
    container_name: avian_mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: avian_phpmyadmin
    restart: always
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PMA_HOST: mysql-db
    depends_on:
      - mysql-db

  # ฝั่งประมวลผล AI (FastAPI)
  fastapi-ai:
    build: ./backend/fastapi
    container_name: avian_fastapi
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql-db

  # ฝั่ง API หลัก (NestJS)
  nestjs-api:
    build: ./backend/nestjs
    container_name: avian_nestjs
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend/nestjs/uploads:/app/uploads
    depends_on:
      mysql-db:
        condition: service_healthy
      fastapi-ai:
        condition: service_started

  react-frontend:
    build: ./frontend
    container_name: avian_react
    restart: always

  nginx:
    image: nginx:latest
    container_name: avian_nginx
    ports:
      - "80:80"  
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nestjs-api
      - fastapi-ai
      - react-frontend

volumes:
  mysql_data: # เอาไว้เซฟข้อมูลตารางฐานข้อมูลไม่ให้หาย